version: '3.9'

services:
  php-apache-env:
    container_name: php-apache
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - "8000:80"
    networks:
      - backend
  db:
    container_name: db
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: 'article'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume:
networks:
  backend: {}
